/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Valquíria Anacleto
 */
public class BuscarFuncionarioView extends javax.swing.JFrame {
  private static BuscarFuncionarioView instancia;
    /**
     * Creates new form ListaFuncionarioView
     */
    public BuscarFuncionarioView() {
         initComponents();
              setLocationRelativeTo(this.getParent());
       
    }
   
    
    public static BuscarFuncionarioView getInstance(){
        if(instancia != null){
              instancia.setVisible(true);
       
        }else{
               instancia = new BuscarFuncionarioView();
        }
        return instancia;
    }
    
    public JTextField getTxtBuscaNome() {
        return txtNomeBuscaFuncionario;
    }
    
    public JButton getBtnFecharVizualizacao() {
        return btnFecharBusca;
    }
    public JButton getBtnNovoFuncionarioVizualizacao() {
        return btnNovoContatoBusca;
    }
    public JButton getBtnBuscaFuncionario() {
        return  btnBuscaNome;
    }
   
    public JButton getBtnVerBonus() {
        return btnVerBonus;
    }
    
     public JButton getBtnVizualizar() {
        return btnVisualizarBusca;
    }
      public JTable getTabela() {
        return jTableFuncionario;
    }
       public JLabel getLblTotal() {
        return lblTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeBuscaFuncionario = new javax.swing.JTextField();
        btnBuscaNome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionario = new javax.swing.JTable();
        btnFecharBusca = new javax.swing.JButton();
        btnNovoContatoBusca = new javax.swing.JButton();
        btnVerBonus = new javax.swing.JButton();
        btnVisualizarBusca = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("Nome");

        txtNomeBuscaFuncionario.setText("  ");

        btnBuscaNome.setText("Buscar");

        jTableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Idade", "função", "Salário Base (R$)"
            }
        ));
        jScrollPane1.setViewportView(jTableFuncionario);

        btnFecharBusca.setText("Fechar");

        btnNovoContatoBusca.setText("Novo contato");
        btnNovoContatoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoContatoBuscaActionPerformed(evt);
            }
        });

        btnVerBonus.setText("Ver bônus");

        btnVisualizarBusca.setText("Visualizar");

        lblTotal.setText("Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnFecharBusca)
                .addGap(103, 103, 103)
                .addComponent(btnNovoContatoBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerBonus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizarBusca)
                .addContainerGap(172, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotal)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFecharBusca)
                    .addComponent(btnNovoContatoBusca)
                    .addComponent(btnVerBonus)
                    .addComponent(btnVisualizarBusca))
                .addGap(13, 13, 13)
                .addComponent(lblTotal))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtNomeBuscaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscaNome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeBuscaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoContatoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoContatoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoContatoBuscaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaNome;
    private javax.swing.JButton btnFecharBusca;
    private javax.swing.JButton btnNovoContatoBusca;
    private javax.swing.JButton btnVerBonus;
    private javax.swing.JButton btnVisualizarBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionario;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtNomeBuscaFuncionario;
    // End of variables declaration//GEN-END:variables
}
